variable "pjname" {}
variable "platform_pjname" {}
variable "vpc_id" {}
variable "private_subnets" {}
variable "order_elasticache_node_type" {}
variable "order_elasticache_parameter_group_name" {}
variable "order_elasticache_engine_version" {}
variable "order_elasticache_port" {}
variable "private_zone_id" {}
variable "private_zone_name" {}
