variable "pjname" {}
variable "location" {}
variable "vnet" {}
variable "aks" {}
variable "common" {}
variable "product" {}
variable "order" {}
variable "dns" {}
variable "nautible_service_principal_object_id" {}
