variable "pjname" {}
variable "platform_pjname" {}
variable "vpc_id" {}
variable "private_subnets" {}
variable "private_zone_id" {}
variable "private_zone_name" {}
variable "eks_node_security_group_ids" {}
variable "engine_version" {}
variable "instance_class" {}
variable "option_group_name" {}
variable "storage_type" {}
variable "allocated_storage" {}
variable "parameter_family" {}
variable "parameters" {}
