variable "pjname" {}
variable "location" {}
variable "subnet_ids" {}
variable "order_redis_capacity" {}
variable "order_redis_family" {}
variable "order_redis_sku_name" {}
variable "cosmosdb_public_network_access_enabled" {}
variable "cosmosdb_enable_free_tier" {}
variable "servicebus_sku" {}
variable "servicebus_max_delivery_count" {}
variable "servicebus_max_size_in_megabytes" {}
