variable "pjname" {}
variable "region" {}
variable "vpc_id" {}
variable "vpc_cidr" {}
variable "public_subnet_ids" {}
variable "private_subnet_ids" {}
variable "create_iam_resources" {}
variable "eks_cluster_version" {}
variable "eks_ng_desired_size" {}
variable "eks_ng_max_size" {}
variable "eks_ng_min_size" {}
variable "eks_ng_instance_type" {}
variable "eks_default_ami_type" {}
variable "eks_default_disk_size" {}
variable "eks_cluster_endpoint_private_access" {}
variable "eks_cluster_endpoint_public_access" {}
variable "eks_cluster_endpoint_public_access_cidrs" {}
variable "eks_cluster_addons_coredns_version" {}
variable "eks_cluster_addons_vpc_cni_version" {}
variable "eks_cluster_addons_kube_proxy_version" {}
variable "eks_fargate_selectors" {}
