variable "pjname" {}
variable "region" {}
variable "vpc_id" {}
variable "vpc_cidr" {}
variable "public_subnet_ids" {}
variable "private_subnet_ids" {}
variable "create_iam_resources" {}
variable "cluster_version" {}
variable "ng_desired_size" {}
variable "ng_max_size" {}
variable "ng_min_size" {}
variable "ng_instance_type" {}
variable "ng_ami_type" {}
variable "ng_disk_size" {}
variable "cluster_endpoint_private_access" {}
variable "cluster_endpoint_public_access" {}
variable "cluster_endpoint_public_access_cidrs" {}
variable "cluster_addons_coredns_version" {}
variable "cluster_addons_vpc_cni_version" {}
variable "cluster_addons_kube_proxy_version" {}
variable "fargate_selectors" {}
variable "albc_security_group_cloudfront_prefix_list_id" {}
