variable "pjname" {}
variable "location" {}
variable "aks_subnet_ids" {}
variable "vnet_id" {}
variable "vnet_rg_name" {}
variable "order_redis_version" {}
variable "order_redis_capacity" {}
variable "order_redis_family" {}
variable "order_redis_sku" {}
variable "servicebus_max_delivery_count" {}
variable "servicebus_max_size_in_megabytes" {}
variable "servicebus_namespace_id" {}
variable "redis_private_dns_zone_id" {}
