variable "pjname" {}
variable "region" {}
variable "vpc_id" {}
variable "vpc_cidr" {}
variable "public_subnet_ids" {}
variable "private_subnet_ids" {}
variable "create_iam_resources" {}
variable "cluster_name" {}
variable "cluster_version" {}
variable "cluster_node_pools" {}
variable "cluster_endpoint_private_access" {}
variable "cluster_endpoint_public_access" {}
variable "cluster_endpoint_public_access_cidrs" {}
variable "cloudwatch_log_group_retention_in_days" {}
variable "albc_security_group_cloudfront_prefix_list_id" {}
