variable "pjname" {}
variable "platform_pjname" {}
variable "region" {}
variable "vpc_id" {}
variable "public_subnets" {}
variable "private_subnets" {}
variable "private_zone_id" {}
variable "private_zone_name" {}
variable "eks_node_security_group_id" {}
variable "eks_oidc_provider_arn" {}
variable "order_elasticache_node_type" {}
variable "order_elasticache_parameter_group_name" {}
variable "order_elasticache_engine_version" {}
variable "order_elasticache_port" {}
