variable "pjname" {}
variable "location" {}
variable "aks_aci_subnet_cidr" {}
variable "product_db_subnet_cidr" {}
variable "product_db_sku" {}
variable "product_db_zone" {}
variable "vnet_id" {}
variable "vnet_name" {}
variable "vnet_rg_name" {}
variable "product_db_administrator_login" {}
variable "product_db_administrator_password" {}
