apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - type: helm
      url: https://kubernetes.github.io/autoscaler/
      name: autoscaler
    - type: helm
      url: https://dapr.github.io/helm-charts/
      name: dapr.io
    - type: helm
      url: https://prometheus-community.github.io/helm-charts/
      name: prometheus-community
    - type: helm
      url: https://aws.github.io/eks-charts/
      name: aws-load-balancer-controller
    - url: https://github.com/nautible/nautible-infra
      name: nautible-infra
    - url: https://github.com/nautible/nautible-plugin
      name: nautible-plugin
    - url: https://github.com/nautible/nautible-app-ms-product-manifest
      name: nautible-app-ms-product-manifest
    - url: https://github.com/nautible/nautible-app-ms-customer-manifest
      name: nautible-app-ms-customer-manifest
    - url: https://github.com/nautible/nautible-app-ms-stock-manifest
      name: nautible-app-ms-stock-manifest
    - url: https://github.com/nautible/nautible-app-ms-order-manifest
      name: nautible-app-ms-order-manifest
    - url: https://github.com/nautible/nautible-app-ms-payment-manifest
      name: nautible-app-ms-payment-manifest
    - url: https://github.com/nautible/nautible-app-ms-delivery-manifest
      name: nautible-app-ms-delivery-manifest
    - url: https://github.com/nautible/nautible-app-examples-manifest
      name: nautible-app-examples-manifest
