variable "pjname" {}
variable "rgname" {}
variable "location" {}
variable "subnet_ids" {}
variable "vnet_id" {}
variable "vnet_name" {}
variable "nautible_service_principal_object_id" {}
variable "keyvault_private_dns_zone_id" {}
variable "postgres_version" {}
variable "postgres_sku_name" {}
variable "postgres_storage_mb" {}
variable "postgres_backup_retention_days" {}
variable "postgres_subnet_cidr" {}
variable "postgres_subnet_name" {}
variable "postgres_zone" {}
variable "postgres_administrator_login" {}
variable "postgres_administrator_password" {}
